spring.application.name=IQuiz
server.port=8404
server.address=0.0.0.0

spring.datasource.url=jdbc:mysql://localhost:3306/iquiz_db
spring.datasource.username=root
#spring.datasource.username=iquiz
spring.datasource.password=123456789
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

gemini.api.key=
gemini.model=gemini-2.5-flash

spring.security.filter.dispatcher-types=REQUEST,ERROR,ASYNC

spring.security.bcrypt.strength=10

springdoc.swagger-ui.path=/swagger
springdoc.api-docs.path=/api-docs
spring.main.allow-circular-references=true

