spring.application.name=QuestifyApp

# Database MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/questify_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.security.filter.dispatcher-types=REQUEST,ERROR,ASYNC

spring.security.bcrypt.strength=10

questify.app.jwtSecret=questifySecretKey1234567890
questify.app.jwtExpirationMs=86400000
